<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icon\icon_child13.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\Debug\net8.0-windows\Resources\**" />
    <EmbeddedResource Remove="bin\Debug\net8.0-windows\Resources\**" />
    <None Remove="bin\Debug\net8.0-windows\Resources\**" />
    <Page Remove="bin\Debug\net8.0-windows\Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".env" />
    <None Remove="Resources\img\image.png" />
    <None Remove="Resources\tessdata_fast\eng.traineddata" />
    <None Remove="Resources\text\correctText.txt" />
    <None Remove="Resources\text\output.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icon\icon_child13.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include=".env" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\img\image.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\tessdata_fast\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\text\correctText.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\text\output.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenAI" Version="2.0.0" />
    <PackageReference Include="Sprache" Version="2.3.1" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Localization\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net8.0-windows\" />
  </ItemGroup>

</Project>
