//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace child13.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("child13.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ вхідного API.
        /// </summary>
        internal static string _btnApi {
            get {
                return ResourceManager.GetString("_btnApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        internal static string _btnClearAll {
            get {
                return ResourceManager.GetString("_btnClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Координати читача.
        /// </summary>
        internal static string _btnCoordinate {
            get {
                return ResourceManager.GetString("_btnCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перша.
        /// </summary>
        internal static string _btnFirst {
            get {
                return ResourceManager.GetString("_btnFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        internal static string _btnFirstClear {
            get {
                return ResourceManager.GetString("_btnFirstClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друга.
        /// </summary>
        internal static string _btnSecond {
            get {
                return ResourceManager.GetString("_btnSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        internal static string _btnSecondClear {
            get {
                return ResourceManager.GetString("_btnSecondClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Третя.
        /// </summary>
        internal static string _btnThird {
            get {
                return ResourceManager.GetString("_btnThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити.
        /// </summary>
        internal static string _btnThirdClear {
            get {
                return ResourceManager.GetString("_btnThirdClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фіксація вікна.
        /// </summary>
        internal static string _btnTompost {
            get {
                return ResourceManager.GetString("_btnTompost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чорний.
        /// </summary>
        internal static string _cbItemBlack {
            get {
                return ResourceManager.GetString("_cbItemBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Білий.
        /// </summary>
        internal static string _cbItemWhite {
            get {
                return ResourceManager.GetString("_cbItemWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Check.
        /// </summary>
        internal static string _lblApi {
            get {
                return ResourceManager.GetString("_lblApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колір тла.
        /// </summary>
        internal static string _lblBack {
            get {
                return ResourceManager.GetString("_lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт:.
        /// </summary>
        internal static string _lblFont {
            get {
                return ResourceManager.GetString("_lblFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розмір:.
        /// </summary>
        internal static string _lblSize {
            get {
                return ResourceManager.GetString("_lblSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це сторінка для перевірки підключення API..
        /// </summary>
        internal static string _txtAPICheck {
            get {
                return ResourceManager.GetString("_txtAPICheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметри тексту та фону.
        /// </summary>
        internal static string _txtSettings {
            get {
                return ResourceManager.GetString("_txtSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Перша зона не вказана.
        /// </summary>
        internal static string _ErrorMessage_First
        {
            get
            {
                return ResourceManager.GetString("_ErrorMessage_First", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Друга зона не вказана.
        /// </summary>
        internal static string _ErrorMessage_Second
        {
            get
            {
                return ResourceManager.GetString("_ErrorMessage_Second", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Третя зона не вказана.
        /// </summary>
        internal static string _ErrorMessage_Third
        {
            get
            {
                return ResourceManager.GetString("_ErrorMessage_Third", resourceCulture);
            }
        }
    }
}
